system:
  listen: :8080
  session_ttl: 24 # 单位：小时

portmap:
  # 监听端口
  38085:
    # 此http映射是否启用
    # enable: true
    # 身份验证器是否启用
    enable_auth: true
    authorization:
      # 身份验证用户名和密码，可多个（符合yaml列表语法）
      anshan: anshan
    # 目标http的地址
    dest: 172.16.59.106:30002

  38086:
    # enable: false
    enable_auth: true
    authorization:
      jwping: jwping
    dest: 172.16.59.106:5319

  38087:
    # enable: false
    enable_auth: true
    authorization:
      jwping: jwping
    dest: 172.16.59.106:38888

  # 38087:
  #   # enable: true
  #   enable_auth: true
  #   authorization:
  #     ops: ops
  #   dest: 172.16.59.106:5320